- name: List archive snapshots
  hosts: localhost
  gather_facts: no

  vars:
    cluster_name: "{{ lookup('env', 'CLUSTER_NAME') | default('cluster1') }}"
    user_name: ansible
    domain: local   # Change to 'myAdDomain.net' for Active Directory
    bucket: "{{ lookup('env', 'Ext_Target') | default('AWS-WORM-S3') }}"
    all_pg:  "{{ lookup('env', 'ALL_PG') | default('false') }}"
    
  tasks:
    - name: Ensure changeLocalRetention.py is executable
      file:
        path: ./archivedSnapshots.py
        mode: '0755'
        state: file
      delegate_to: localhost

    - name: Run archivedSnapshots.py to list archived snapshots
      command: >
        ./archivedSnapshots.py
        -v {{ cluster_name }}
        -u {{ user_name }}
        -d {{ domain }}
        -pwd "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
        -t {{ bucket }}
        -l joblist
        {% if  not all_pg | bool %}
        -l joblist
        {% endif %}
                
      register: archive_list
      delegate_to: localhost
    
    - name: Save archive snapshot list to file
      copy:
        dest: ./archive_list.txt
        content: "{{ archive_list.stdout }}"
      delegate_to: localhost
